version: "3.2"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - 5005:5005

  ejabberd:
    build:
      context: .
      dockerfile: Dockerfile.ejabberd
    ports:
      - 5222:5222
      - 5280:5280
      - 5443:5443
    volumes:
      - ./conf/ejabberd.yml:/opt/ejabberd/conf/ejabberd.yml
