version: "3.2"

services:
  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - 5005:5005

  unexposed-jabber:
    build:
      context: .
      dockerfile: Dockerfile.ejabberd
    volumes:
      - ./conf/ejabberd.yml:/opt/ejabberd/conf/ejabberd.yml
    # ports: [5280:5280] # uncomment for dev/demo purposes, it should generally stay inaccessible
